apiVersion: v1
kind: Service
metadata:
  name: archinsight-ai-analyzer-service
spec:
  type: LoadBalancer
  selector:
    app: archinsight-ai-analyzer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
